# Generated by Django 4.2.15 on 2024-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extrinsic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrinsic_address', models.CharField(max_length=100)),
                ('extrinsic_hash', models.CharField(max_length=100)),
                ('extrinsic_netuid', models.IntegerField()),
                ('extrinsic_block', models.IntegerField()),
                ('extrinsic_idx', models.CharField(max_length=10)),
                ('block_hash', models.CharField(max_length=100)),
            ],
        ),
    ]
