# Generated by Django 4.2.15 on 2024-08-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extrinsic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('netuid', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('block_number', models.IntegerField()),
                ('idx', models.IntegerField()),
                ('block_hash', models.CharField(max_length=64)),
                ('signature', models.JSONField()),
                ('tip', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('era', models.CharField(max_length=10)),
                ('call_index', models.CharField(max_length=10)),
                ('call_function', models.CharField(max_length=100)),
                ('call_module', models.CharField(max_length=100)),
                ('call_args', models.JSONField()),
                ('result', models.CharField(max_length=20)),
                ('events', models.JSONField()),
            ],
        ),
    ]
