# Generated by Django 4.2.15 on 2024-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrinsic',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='block_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='block_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='call_args',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='call_function',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='call_index',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='call_module',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='era',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='events',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='idx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='netuid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='nonce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='result',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='signature',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='extrinsic',
            name='tip',
            field=models.IntegerField(null=True),
        ),
    ]
